version: "3"
services:
  app:
    build: .
    volumes:
      - .:/webapp/current
      - /run:/tmp
    links:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: docker-rails-parallel-tests
    ports:
      - "3333:3333"
  db:
    image: postgres:9.6
    ports:
      - "5432"
    volumes:
      - ~/data/postgres/9.6:/var/lib/postgresql/data
